### PR TITLE
Avoid erroring out if the crashing_thread is malformed somehow

### PR DESCRIPTION
**Pull request by staktrace**

### CODE REVIEW

**Comment by staktrace** [comment]
Thanks, feel free to merge it, unless there's a reason not to? I don't know if there's a process for changes here (need to file a bug etc.)

**Comment by willkg** [comment]
I don't know who "owns" this repo. I was thinking @wlach did.

**Comment by wlach** [comment]
> I don't know who "owns" this repo. I was thinking @wlach did.

Me, @willkg, and @Ben-Wu are admins on the repo. I'd be happy to add @staktrace to that list. At this point the project IMO isn't well-defined enough to warrant thinking harder about repo governance. If we wind up using it in a production system we can revisit.

In the future, @willkg feel free to merge stuff if it looks good, I trust you. :) I'll handle this one.

**Comment by willkg** [comment]
Since the point of this repo is to get signatures for crash pings and @staktrace is driving that, I vote he should be an admin and can move this project forward. I'm happy to help with reviewing and whatever else needs helping with, but I don't use this project.

**Comment by wlach** [comment]
> Since the point of this repo is to get signatures for crash pings and @staktrace is driving that, I vote he should be an admin and can move this project forward. I'm happy to help with reviewing and whatever else needs helping with, but I don't use this project.

Makes sense to me, I'll add him to the list.

**Pull request merged**
